### ISSUE TITLE
Google redirection clean not working: add decodeURIComponent()

### ISSUE THREAD

**Issue by ltGuillaume** [Cimbali/CleanLinks#73] opened 2019-08-18 18:17 UTC
`https://www.google.com/url?q=https://some.thing/forum/viewtopic.php%3Ft%3D4960084`
is replaced by
`https://some.thing/forum/viewtopic.php%3Ft%3D4960084`
which gives a 404, because decodeURIComponent() is not called beforehand. Doing this would result in
`https://some.thing/forum/viewtopic.php?t=4960084` and a correct loading of the address.

Waterfox 56, CleanLinks 3.2.7

**Comment by Cimbali** [comment] 2019-08-18 20:43
Hi @ltGuillaume, thanks for reporting the bug. I’m suspecting this might be a duplicate of #67. Are you blocking javascript on google?

In any case, it seems the problem comes from the fact that Google should encode the URI component correctly, that is:

   https://www.google.com/url?q=https%3A%2F%2Fsome.thing%2Fforum%2Fviewtopic.php%3Ft%3D4960084

Some websites use unencoded destination URLs, so we also detect those. If we fail to detect them, we then try with decoded URI Components. However this approach conflicts when the destination URL is ambiguously encoded ( like on google without javascript with `:` and `/` unencoded but `?`, `=` and `&` encoded).

**Comment by ltGuillaume** [comment] 2019-08-18 21:34
I'm not using uMatrix, only uBlock Origin and I'm not blocking Javascript on Google.

It turns out my report was incomplete: though google.com search results get cleaned properly, Google's __Custom Search__ results on other pages do not work. Example: https://torrentdownloads.be

**Comment by Grossdm** [comment] 2020-01-29 01:45
I just tried the search on https://torrentdownloads.be/ and the results were cleaned for me.

**Closed** 2020-03-04 16:44 UTC
