### ISSUE TITLE
Can't open links in new tab

### ISSUE THREAD

**Issue by nerone** [Cimbali/CleanLinks#22] opened 2018-06-08 07:17 UTC
While using extension it's not possible to open links in new tab when using keyboard shortcut **Cmd/Ctrl +** link. Reproducible on google.com.

**Comment by Cimbali** [comment] 2018-06-08 16:33
Works for me, both with scroll-button click and ctrl + click. even the "switch to tab" option

 Can you be more specific? CleanLinks version, Firefox version, platform? Thanks

**Comment by Imold** [comment] 2018-06-08 19:31
I can confirm that middle click and control left click both open the link in the current tab, not in a new tab.
Browser: Waterfox 56.2.0 (64-bit)

**Comment by Cimbali** [comment] 2018-06-08 20:04
Interesting. You have outgoing HTTP requests cleaning disabled, is that right?

It appears if you activate it the request gets denied, and on a second click it then works. Both work fine on firefox 60.0.

**Comment by Cimbali** [comment] 2018-06-08 20:37
Turns out we use the [openerTabId property](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create#Browser_compatibility) which is compatible with ff 57+, to indicate to which tab to return on closing the new tab. We'll probably need to figure out which is the lowest version we want to support and account for that.

**Comment by nerone** [comment] 2018-06-12 07:20
Did a bit of testing. 
I can still reproduce this using v3.0.3 on clean Firefox 60.0.2 install on OS X 10.11.6. But I have tried on Windows and it works as expected.

**Comment by Cimbali** [comment] 2018-06-12 14:14
Can you maybe open the Console (Ctrl + Alt + Shift + i, it's going to ask for remote debugging confirmation) to check for error messages?

Basically on the toolbox that the shortcut opens, go to the Console tab, purge the history for ease of reading (trash can in the top left corner), and click a link that fails.

There should be an error message from either cleanlink.js, background.js or inject.js which are the 3 CleanLinks scripts involved.

**Comment by nerone** [comment] 2018-06-12 18:42
I tried add-on debugging console, but it shows nothing related to Clean Links extension when I Cmd + click on links in Google search results.

**Comment by Cimbali** [comment] 2018-06-13 14:59
Ah, my bad, the error doesn't show because there already is a fallback in case of error. I've added a print, in the [debug_print_22](/Cimbali/CleanLinks/tree/debug_print_22) branch.

I don't have a mac to reproduce this, so what would be helpful to debug this issue would be for you to get that branch with the debug print, and report the error.

Here's a step by step guide:
- get the [debug_print_22](/Cimbali/CleanLinks/tree/debug_print_22) branch (there is a zip download in the "Clone or download" button)
- extract the zip if you downloaded the addon zipped
- disable your current cleanlinks in your browser
- type `about:debugging#addons` in your firefox address bar
- tick "Enable add-on debugging"
- click "Load Temporary Addon"
- select the `manifest.json` file from the source code you just downloaded/extracted

Now just repeat the steps to look at the debugging console while doing Cmd + Click and an error message should appear. You can filter the console by "Logging > Errors" using the buttons in the top row.

**Comment by nerone** [comment] 2018-06-14 10:47
![clean-links](https://user-images.githubusercontent.com/1044142/41407827-4b91f8ec-6fd9-11e8-9389-67431826cef5.png)

I get only this in console when Google search results loaded and nothing else when Cmd + clicking on links.

**Comment by Cimbali** [comment] 2018-06-14 12:57
Alright, well that's a start. Maybe that exception in the background script prevented it from correctly opening a new window later on or something. I fixed it, now let's see if it works.

**Comment by nerone** [comment] 2018-06-14 13:07
Now that error has gone and no other appear.

**Comment by nerone** [comment] 2018-06-19 11:53
@Cimbali, can you please re-open the issue, if it’s not already fixed?

**Comment by Cimbali** [comment] 2018-06-20 22:31
@nerone My main problem with this issue is just that I can't reproduce it. It is fixed for Waterfox and FF < 57 though, just not your setup.

**Comment by Bt7fdbufffdk** [comment] 2019-06-09 06:49
this issue also occurs on reddit when clicking on any of those types of links shown in the screenshot
<img width="350" alt="sfdgchvjb" src="https://user-images.githubusercontent.com/51258116/59155931-6c880a00-8ad6-11e9-8c8b-05d8324c0b38.png">

**Closed** 2020-03-04 18:06 UTC
Labels: bug, more info needed

**Comment by Cimbali** [comment] 2020-03-04 18:07
I think this is actually a really simple bug now I look back at it. We recreated the `ctrl + click` behaviour manually:

https://github.com/Cimbali/CleanLinks/blob/dbcdb4ff53841c681607223c2a40f0c1c529dac0/addon/inject.js#L37-L38

On macOS the default is to use `cmd + click` instead of `ctrl + click`. So now we check for both. There should not be too much interference from `meta + click` on other OSs, and `ctrl + click` opens the context menu on macOS, so this should also be safe if we don’t accidentally overwrite it.

Some testing on macOS still needs to happen.

**Comment by Cimbali** [comment] 2020-03-04 20:22
I can confirm this now works as expected.
